/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JPConsultarEmprestimo.java
 *
 * Created on 07/05/2012, 22:09:01
 */
package presentation.emprestimo;

import business.BusinessException;
import business.BusinessFactory;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import presentation.desktop.MainWindow;
import util.NumberRenderer;
import vo.EmprestimoVO;
import vo.UsuarioVO;

/**
 *
 * @author Endril
 */
public class JPConsultarEmprestimo extends javax.swing.JPanel implements presentation.lib.ReturnEvent {

    private List<EmprestimoVO> emprestimos;
    /** Creates new form JPConsultarEmprestimo */
    public JPConsultarEmprestimo() {
        initComponents();
        TableColumnModel m = jTable2.getColumnModel();
        m.getColumn(4).setCellRenderer(NumberRenderer.getCurrencyRenderer());
        m.getColumn(4).setMaxWidth(100);
        this.populaTabela();
              
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 30));
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("I18n/Bundle"); // NOI18N
        jLabel1.setText(bundle.getString("JPConsultarEmprestimo.jLabel1.text")); // NOI18N

        jButton2.setFont(new java.awt.Font("Calibri", 1, 12));
        jButton2.setText(bundle.getString("JPConsultarEmprestimo.jButton2.text")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable2.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Credor", "Devedor", "Data do Empréstimo", "Descrição", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        jTable2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jTable2);
        jTable2.getColumnModel().getColumn(0).setHeaderValue(bundle.getString("JPConsultarEmprestimo.jTable2.columnModel.title3")); // NOI18N
        jTable2.getColumnModel().getColumn(1).setHeaderValue(bundle.getString("JPConsultarEmprestimo.jTable2.columnModel.title4")); // NOI18N
        jTable2.getColumnModel().getColumn(2).setHeaderValue(bundle.getString("JPConsultarEmprestimo.jTable2.columnModel.title1")); // NOI18N
        jTable2.getColumnModel().getColumn(3).setHeaderValue(bundle.getString("JPConsultarEmprestimo.jTable2.columnModel.title2")); // NOI18N
        jTable2.getColumnModel().getColumn(4).setResizable(false);
        jTable2.getColumnModel().getColumn(4).setPreferredWidth(70);
        jTable2.getColumnModel().getColumn(4).setHeaderValue(bundle.getString("JPConsultarEmprestimo.jTable2.columnModel.title2_1")); // NOI18N

        jButton3.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jButton3.setText(bundle.getString("JPConsultarEmprestimo.jButton3.text")); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 479, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       MainWindow.getInstance().closeCurrentCard();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(jTable2.getSelectedRow() >= 0){
            ResourceBundle bundle = ResourceBundle.getBundle("I18n/Bundle");
            if(JOptionPane.YES_OPTION == JOptionPane.showConfirmDialog(this, bundle.getString("JPConsultarEmprestimo.Messages.ConfirmaRemocaoLn1")+"\n"+bundle.getString("JPConsultarEmprestimo.Messages.ConfirmaRemocaoLn2"), bundle.getString("JPUsuariosCadastrados.Messages.ConfirmaRemocaoTitle"), JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE)){
                EmprestimoVO selecionado = emprestimos.get((this.jTable2.getSelectedRow()));
                BusinessFactory factory = BusinessFactory.getInstance();
                try{
                    factory.getEmprestimo().delete(selecionado);
                }
                catch(BusinessException e){

                }
                this.repopulaTabela();
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables

    public void onReturnFromOtherWindow(Object returnedObject) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    private void repopulaTabela() {
        ((DefaultTableModel)jTable2.getModel()).setRowCount(0);
        this.populaTabela();
    }

    private void populaTabela() {
        int counter = 0;
        try {
            List<ArrayList> emprestimosComUsers = BusinessFactory.getInstance().getEmprestimo().getAllWithUsers();
            DefaultTableModel model =(DefaultTableModel) jTable2.getModel();
            emprestimos = new ArrayList<EmprestimoVO>();
            for (ArrayList listElement:emprestimosComUsers) {
                EmprestimoVO emprestimo = (EmprestimoVO) listElement.get(0);
                emprestimos.add(emprestimo);
                UsuarioVO usuarioCredor = (UsuarioVO) listElement.get(1);
                UsuarioVO usuarioDevedor = (UsuarioVO) listElement.get(2);

                DateFormat df = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
                model.insertRow(counter,new Object[]{usuarioCredor.getNome(), usuarioDevedor.getNome(), df.format(emprestimo.getDataHora().getTime()),emprestimo.getDescricao(),emprestimo.getValor()});
                counter++;
            }
            jTable2.changeSelection(0, 0, false, false);
        } catch (BusinessException ex) {
            Logger.getLogger(JPConsultarEmprestimo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
}
